# Generated by Django 2.1.3 on 2019-01-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('bed', 'Bed'), ('floor', 'Floor'), ('couch', 'Couch')], max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_arrangements.House')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='spot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='house_arrangements.Spot'),
        ),
    ]
