# Generated by Django 2.1.3 on 2018-12-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_arrangements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='people',
            field=models.ManyToManyField(blank=True, to='house_arrangements.Person'),
        ),
    ]
