# Generated by Django 2.1.3 on 2018-12-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_arrangements', '0002_auto_20181212_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('bed', 'Bed'), ('floor', 'Floor')], max_length=200)),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='house_arrangements.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='people',
        ),
        migrations.AddField(
            model_name='house',
            name='guest_spots',
            field=models.ManyToManyField(to='house_arrangements.Spot'),
        ),
    ]
