# Generated by Django 2.1.3 on 2018-12-14 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_arrangements', '0003_auto_20181214_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house_arrangements.Person'),
        ),
    ]
