# Generated by Django 2.1.3 on 2018-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_arrangements', '0004_auto_20181214_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bed_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='floor_spots',
            field=models.IntegerField(default=0),
        ),
    ]
